DECLARE
  user_count INTEGER;
  table_space_count INTEGER;
BEGIN

  -- Test stuff
  -- Test tablespace
  SELECT 
    COUNT(*) into table_space_count
  FROM 
    dba_tablespaces 
  WHERE 
    tablespace_name = 'TESTTABLES';
    
  IF table_space_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SMALLFILE TABLESPACE TESTTABLES DATAFILE ''TESTTABLES.DBF'' SIZE 50M AUTOEXTEND ON';
  END IF;

  -- Test indexspace
  SELECT 
    COUNT(*) into table_space_count
  FROM 
    dba_tablespaces 
  WHERE 
    tablespace_name = 'TESTINDICES';
    
  IF table_space_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SMALLFILE TABLESPACE TESTINDICES DATAFILE ''TESTINDICES.DBF'' SIZE 10M AUTOEXTEND ON';
  END IF;

  -- Test Developer account
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'TEST';
    
  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER TEST IDENTIFIED BY TESTdev#';  
    EXECUTE IMMEDIATE 'ALTER USER TEST DEFAULT TABLESPACE TESTTABLES QUOTA UNLIMITED ON TESTTABLES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO TEST';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO TEST';
  END IF; 

  -- Runtime server account
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'TESTSERVER';

  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER TESTSERVER IDENTIFIED BY TEST5erver';
    EXECUTE IMMEDIATE 'ALTER USER TESTSERVER DEFAULT TABLESPACE TESTTABLES QUOTA UNLIMITED ON TESTTABLES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO TESTSERVER';    
    
  END IF;
  
  ---------------------------------------------------------------------------------------------------------------------
  -- CCG stuff
  -- Table space
  SELECT 
    COUNT(*) into table_space_count
  FROM 
    dba_tablespaces 
  WHERE 
    tablespace_name = 'CCGTABLES';
    
  IF table_space_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SMALLFILE TABLESPACE CCGTABLES DATAFILE ''CCGTABLES.DBF'' SIZE 200M AUTOEXTEND ON';
  END IF;

  -- CCG indexspace
  SELECT 
    COUNT(*) into table_space_count
  FROM 
    dba_tablespaces 
  WHERE 
    tablespace_name = 'CCGINDICES';
    
  IF table_space_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SMALLFILE TABLESPACE CCGINDICES DATAFILE ''CCGINDICES.DBF'' SIZE 50M AUTOEXTEND ON';
  END IF;
  
  -- Developer account
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'CCG';
    
  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CCG IDENTIFIED BY CCGdev#';  
    EXECUTE IMMEDIATE 'ALTER USER CCG DEFAULT TABLESPACE CCGTABLES QUOTA UNLIMITED ON CCGTABLES';
    EXECUTE IMMEDIATE 'ALTER USER CCG QUOTA UNLIMITED ON CCGINDICES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CCG';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO CCG';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO CCG';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO CCG';
/*    
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, ALTER TABLE, DROP TABLE, CREATE PROCEDURE, ALTER PROCEDURE, DROP PROCEDURE TO CCG;';
    EXECUTE IMMEDIATE 'GRANT CREATE INDEX,  TO CCG;';
*/    
  END IF; 

  -- Runtime server account
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'CCGSERVER';

  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CCGSERVER IDENTIFIED BY CCG5erver';
    EXECUTE IMMEDIATE 'ALTER USER CCGSERVER DEFAULT TABLESPACE CCGTABLES QUOTA UNLIMITED ON CCGTABLES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CCGSERVER';    
    
  END IF;

  -- Reporting/Analytics account  
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'CCGREPORT';

  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CCGREPORT IDENTIFIED BY CCGRep0rt';
    EXECUTE IMMEDIATE 'ALTER USER CCG DEFAULT TABLESPACE CCGTABLES QUOTA UNLIMITED ON CCGTABLES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CCGREPORT';    
    
  END IF;  
END;




