DECLARE
  user_count INTEGER;
  table_space_count INTEGER;
BEGIN

  -- Table space
  SELECT 
    COUNT(*) into table_space_count
  FROM 
    dba_tablespaces 
  WHERE 
    tablespace_name = 'CCGTABLES';
    
  IF table_space_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SMALLFILE TABLESPACE CCGTABLES DATAFILE ''CCGTABLES.DBF'' SIZE 200M AUTOEXTEND ON';
  END IF;
  
  -- Developer account
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'CCG';
    
  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CCG IDENTIFIED BY CCGdev#';  
    EXECUTE IMMEDIATE 'ALTER USER CCG DEFAULT TABLESPACE CCGTABLES QUOTA UNLIMITED ON CCGTABLES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CCG';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO CCG';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO CCG';
/*    
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, ALTER TABLE, DROP TABLE, CREATE PROCEDURE, ALTER PROCEDURE, DROP PROCEDURE TO CCG;';
    EXECUTE IMMEDIATE 'GRANT CREATE INDEX,  TO CCG;';
*/    
  END IF; 

  -- Runtime server account
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'CCGSERVER';

  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CCGSERVER IDENTIFIED BY CCG5erver';
    EXECUTE IMMEDIATE 'ALTER USER CCG DEFAULT TABLESPACE CCGTABLES QUOTA UNLIMITED ON CCGTABLES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CCGSERVER';    
    
  END IF;

  -- Reporting/Analytics account  
  SELECT
    COUNT(*) into user_count
  FROM
    dba_users
  WHERE
    USERNAME = 'CCGREPORT';

  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CCGREPORT IDENTIFIED BY CCGRep0rt';
    EXECUTE IMMEDIATE 'ALTER USER CCG DEFAULT TABLESPACE CCGTABLES QUOTA UNLIMITED ON CCGTABLES';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CCGREPORT';    
    
  END IF;  
END;




