USE testdb;
CREATE USER test FOR LOGIN test;
CREATE USER testserver FOR LOGIN testserver;
GO

USE ccgdb;
CREATE USER ccg FOR LOGIN ccg;
CREATE USER ccgserver FOR LOGIN ccgserver;
GO

USE testdb;
GRANT CREATE TABLE TO test;
GRANT ALTER ON SCHEMA ::dynamic TO test;
GRANT ALTER ON SCHEMA ::enum TO test;
GRANT ALTER ON SCHEMA ::static TO test;
GRANT REFERENCES ON SCHEMA ::dynamic TO test;
GRANT REFERENCES ON SCHEMA ::enum TO test;
GRANT REFERENCES ON SCHEMA ::static TO test;
GRANT CREATE PROCEDURE TO test;
GRANT CREATE FUNCTION TO test;
GRANT EXECUTE TO test;
GRANT INSERT TO test;
GRANT SELECT TO test;
GRANT UPDATE TO test;

GRANT EXECUTE TO testserver;
GO

USE ccgdb;
GRANT CREATE TABLE TO ccg;
GRANT ALTER ON SCHEMA ::dynamic TO ccg;
GRANT ALTER ON SCHEMA ::enum TO ccg;
GRANT ALTER ON SCHEMA ::static TO ccg;
GRANT REFERENCES ON SCHEMA ::dynamic TO ccg;
GRANT REFERENCES ON SCHEMA ::enum TO ccg;
GRANT REFERENCES ON SCHEMA ::static TO ccg;
GRANT CREATE PROCEDURE TO ccg;
GRANT CREATE FUNCTION TO ccg;
GRANT EXECUTE TO ccg;
GRANT INSERT TO ccg;
GRANT SELECT TO ccg;
GRANT UPDATE TO ccg;

GRANT EXECUTE TO ccgserver;
GO
