//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g 2012-12-02 14:50:15

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
public partial class EnumReflectorLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int BITFIELD=4;
	public const int COMMA=5;
	public const int DIGIT=6;
	public const int ENUM=7;
	public const int ENUM_BEGIN=8;
	public const int ENUM_END=9;
	public const int ENUM_ENTRY=10;
	public const int EQUALS=11;
	public const int EXTENDS=12;
	public const int HEX_DIGIT=13;
	public const int ID=14;
	public const int LBRACE=15;
	public const int LEFT_SHIFT=16;
	public const int LPAREN=17;
	public const int META=18;
	public const int NAMESPACE=19;
	public const int POSITIVE_INTEGER10=20;
	public const int POSITIVE_INTEGER16=21;
	public const int POS_DIGIT=22;
	public const int RBRACE=23;
	public const int RPAREN=24;
	public const int SEMICOLON=25;
	public const int STRING=26;
	public const int WHITESPACE=27;

    // delegates
    // delegators

	public EnumReflectorLexer()
	{
		OnCreated();
	}

	public EnumReflectorLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public EnumReflectorLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_BITFIELD();
	partial void LeaveRule_BITFIELD();

	// $ANTLR start "BITFIELD"
	[GrammarRule("BITFIELD")]
	private void mBITFIELD()
	{
		EnterRule_BITFIELD();
		EnterRule("BITFIELD", 1);
		TraceIn("BITFIELD", 1);
		try
		{
			int _type = BITFIELD;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:7:10: ( 'BITFIELD' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:7:12: 'BITFIELD'
			{
			DebugLocation(7, 12);
			Match("BITFIELD"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BITFIELD", 1);
			LeaveRule("BITFIELD", 1);
			LeaveRule_BITFIELD();
		}
	}
	// $ANTLR end "BITFIELD"

	partial void EnterRule_COMMA();
	partial void LeaveRule_COMMA();

	// $ANTLR start "COMMA"
	[GrammarRule("COMMA")]
	private void mCOMMA()
	{
		EnterRule_COMMA();
		EnterRule("COMMA", 2);
		TraceIn("COMMA", 2);
		try
		{
			int _type = COMMA;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:8:7: ( ',' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:8:9: ','
			{
			DebugLocation(8, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMA", 2);
			LeaveRule("COMMA", 2);
			LeaveRule_COMMA();
		}
	}
	// $ANTLR end "COMMA"

	partial void EnterRule_ENUM();
	partial void LeaveRule_ENUM();

	// $ANTLR start "ENUM"
	[GrammarRule("ENUM")]
	private void mENUM()
	{
		EnterRule_ENUM();
		EnterRule("ENUM", 3);
		TraceIn("ENUM", 3);
		try
		{
			int _type = ENUM;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:9:6: ( 'enum' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:9:8: 'enum'
			{
			DebugLocation(9, 8);
			Match("enum"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ENUM", 3);
			LeaveRule("ENUM", 3);
			LeaveRule_ENUM();
		}
	}
	// $ANTLR end "ENUM"

	partial void EnterRule_ENUM_BEGIN();
	partial void LeaveRule_ENUM_BEGIN();

	// $ANTLR start "ENUM_BEGIN"
	[GrammarRule("ENUM_BEGIN")]
	private void mENUM_BEGIN()
	{
		EnterRule_ENUM_BEGIN();
		EnterRule("ENUM_BEGIN", 4);
		TraceIn("ENUM_BEGIN", 4);
		try
		{
			int _type = ENUM_BEGIN;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:10:12: ( 'EnumBegin' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:10:14: 'EnumBegin'
			{
			DebugLocation(10, 14);
			Match("EnumBegin"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ENUM_BEGIN", 4);
			LeaveRule("ENUM_BEGIN", 4);
			LeaveRule_ENUM_BEGIN();
		}
	}
	// $ANTLR end "ENUM_BEGIN"

	partial void EnterRule_ENUM_END();
	partial void LeaveRule_ENUM_END();

	// $ANTLR start "ENUM_END"
	[GrammarRule("ENUM_END")]
	private void mENUM_END()
	{
		EnterRule_ENUM_END();
		EnterRule("ENUM_END", 5);
		TraceIn("ENUM_END", 5);
		try
		{
			int _type = ENUM_END;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:11:10: ( 'EnumEnd' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:11:12: 'EnumEnd'
			{
			DebugLocation(11, 12);
			Match("EnumEnd"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ENUM_END", 5);
			LeaveRule("ENUM_END", 5);
			LeaveRule_ENUM_END();
		}
	}
	// $ANTLR end "ENUM_END"

	partial void EnterRule_ENUM_ENTRY();
	partial void LeaveRule_ENUM_ENTRY();

	// $ANTLR start "ENUM_ENTRY"
	[GrammarRule("ENUM_ENTRY")]
	private void mENUM_ENTRY()
	{
		EnterRule_ENUM_ENTRY();
		EnterRule("ENUM_ENTRY", 6);
		TraceIn("ENUM_ENTRY", 6);
		try
		{
			int _type = ENUM_ENTRY;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:12:12: ( 'EnumEntry' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:12:14: 'EnumEntry'
			{
			DebugLocation(12, 14);
			Match("EnumEntry"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ENUM_ENTRY", 6);
			LeaveRule("ENUM_ENTRY", 6);
			LeaveRule_ENUM_ENTRY();
		}
	}
	// $ANTLR end "ENUM_ENTRY"

	partial void EnterRule_EQUALS();
	partial void LeaveRule_EQUALS();

	// $ANTLR start "EQUALS"
	[GrammarRule("EQUALS")]
	private void mEQUALS()
	{
		EnterRule_EQUALS();
		EnterRule("EQUALS", 7);
		TraceIn("EQUALS", 7);
		try
		{
			int _type = EQUALS;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:13:8: ( '=' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:13:10: '='
			{
			DebugLocation(13, 10);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("EQUALS", 7);
			LeaveRule("EQUALS", 7);
			LeaveRule_EQUALS();
		}
	}
	// $ANTLR end "EQUALS"

	partial void EnterRule_EXTENDS();
	partial void LeaveRule_EXTENDS();

	// $ANTLR start "EXTENDS"
	[GrammarRule("EXTENDS")]
	private void mEXTENDS()
	{
		EnterRule_EXTENDS();
		EnterRule("EXTENDS", 8);
		TraceIn("EXTENDS", 8);
		try
		{
			int _type = EXTENDS;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:14:9: ( 'extends' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:14:11: 'extends'
			{
			DebugLocation(14, 11);
			Match("extends"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("EXTENDS", 8);
			LeaveRule("EXTENDS", 8);
			LeaveRule_EXTENDS();
		}
	}
	// $ANTLR end "EXTENDS"

	partial void EnterRule_LBRACE();
	partial void LeaveRule_LBRACE();

	// $ANTLR start "LBRACE"
	[GrammarRule("LBRACE")]
	private void mLBRACE()
	{
		EnterRule_LBRACE();
		EnterRule("LBRACE", 9);
		TraceIn("LBRACE", 9);
		try
		{
			int _type = LBRACE;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:15:8: ( '{' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:15:10: '{'
			{
			DebugLocation(15, 10);
			Match('{'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LBRACE", 9);
			LeaveRule("LBRACE", 9);
			LeaveRule_LBRACE();
		}
	}
	// $ANTLR end "LBRACE"

	partial void EnterRule_LEFT_SHIFT();
	partial void LeaveRule_LEFT_SHIFT();

	// $ANTLR start "LEFT_SHIFT"
	[GrammarRule("LEFT_SHIFT")]
	private void mLEFT_SHIFT()
	{
		EnterRule_LEFT_SHIFT();
		EnterRule("LEFT_SHIFT", 10);
		TraceIn("LEFT_SHIFT", 10);
		try
		{
			int _type = LEFT_SHIFT;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:16:12: ( '<<' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:16:14: '<<'
			{
			DebugLocation(16, 14);
			Match("<<"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LEFT_SHIFT", 10);
			LeaveRule("LEFT_SHIFT", 10);
			LeaveRule_LEFT_SHIFT();
		}
	}
	// $ANTLR end "LEFT_SHIFT"

	partial void EnterRule_LPAREN();
	partial void LeaveRule_LPAREN();

	// $ANTLR start "LPAREN"
	[GrammarRule("LPAREN")]
	private void mLPAREN()
	{
		EnterRule_LPAREN();
		EnterRule("LPAREN", 11);
		TraceIn("LPAREN", 11);
		try
		{
			int _type = LPAREN;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:17:8: ( '(' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:17:10: '('
			{
			DebugLocation(17, 10);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LPAREN", 11);
			LeaveRule("LPAREN", 11);
			LeaveRule_LPAREN();
		}
	}
	// $ANTLR end "LPAREN"

	partial void EnterRule_META();
	partial void LeaveRule_META();

	// $ANTLR start "META"
	[GrammarRule("META")]
	private void mMETA()
	{
		EnterRule_META();
		EnterRule("META", 12);
		TraceIn("META", 12);
		try
		{
			int _type = META;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:18:6: ( '//:' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:18:8: '//:'
			{
			DebugLocation(18, 8);
			Match("//:"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("META", 12);
			LeaveRule("META", 12);
			LeaveRule_META();
		}
	}
	// $ANTLR end "META"

	partial void EnterRule_NAMESPACE();
	partial void LeaveRule_NAMESPACE();

	// $ANTLR start "NAMESPACE"
	[GrammarRule("NAMESPACE")]
	private void mNAMESPACE()
	{
		EnterRule_NAMESPACE();
		EnterRule("NAMESPACE", 13);
		TraceIn("NAMESPACE", 13);
		try
		{
			int _type = NAMESPACE;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:19:11: ( 'namespace' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:19:13: 'namespace'
			{
			DebugLocation(19, 13);
			Match("namespace"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NAMESPACE", 13);
			LeaveRule("NAMESPACE", 13);
			LeaveRule_NAMESPACE();
		}
	}
	// $ANTLR end "NAMESPACE"

	partial void EnterRule_RBRACE();
	partial void LeaveRule_RBRACE();

	// $ANTLR start "RBRACE"
	[GrammarRule("RBRACE")]
	private void mRBRACE()
	{
		EnterRule_RBRACE();
		EnterRule("RBRACE", 14);
		TraceIn("RBRACE", 14);
		try
		{
			int _type = RBRACE;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:20:8: ( '}' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:20:10: '}'
			{
			DebugLocation(20, 10);
			Match('}'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RBRACE", 14);
			LeaveRule("RBRACE", 14);
			LeaveRule_RBRACE();
		}
	}
	// $ANTLR end "RBRACE"

	partial void EnterRule_RPAREN();
	partial void LeaveRule_RPAREN();

	// $ANTLR start "RPAREN"
	[GrammarRule("RPAREN")]
	private void mRPAREN()
	{
		EnterRule_RPAREN();
		EnterRule("RPAREN", 15);
		TraceIn("RPAREN", 15);
		try
		{
			int _type = RPAREN;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:21:8: ( ')' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:21:10: ')'
			{
			DebugLocation(21, 10);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RPAREN", 15);
			LeaveRule("RPAREN", 15);
			LeaveRule_RPAREN();
		}
	}
	// $ANTLR end "RPAREN"

	partial void EnterRule_SEMICOLON();
	partial void LeaveRule_SEMICOLON();

	// $ANTLR start "SEMICOLON"
	[GrammarRule("SEMICOLON")]
	private void mSEMICOLON()
	{
		EnterRule_SEMICOLON();
		EnterRule("SEMICOLON", 16);
		TraceIn("SEMICOLON", 16);
		try
		{
			int _type = SEMICOLON;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:22:11: ( ';' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:22:13: ';'
			{
			DebugLocation(22, 13);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("SEMICOLON", 16);
			LeaveRule("SEMICOLON", 16);
			LeaveRule_SEMICOLON();
		}
	}
	// $ANTLR end "SEMICOLON"

	partial void EnterRule_ID();
	partial void LeaveRule_ID();

	// $ANTLR start "ID"
	[GrammarRule("ID")]
	private void mID()
	{
		EnterRule_ID();
		EnterRule("ID", 17);
		TraceIn("ID", 17);
		try
		{
			int _type = ID;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:79:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:79:7: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			{
			DebugLocation(79, 7);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(79, 31);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:79:31: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if (((LA1_0>='0' && LA1_0<='9')||(LA1_0>='A' && LA1_0<='Z')||LA1_0=='_'||(LA1_0>='a' && LA1_0<='z')))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:
					{
					DebugLocation(79, 31);
					input.Consume();


					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ID", 17);
			LeaveRule("ID", 17);
			LeaveRule_ID();
		}
	}
	// $ANTLR end "ID"

	partial void EnterRule_WHITESPACE();
	partial void LeaveRule_WHITESPACE();

	// $ANTLR start "WHITESPACE"
	[GrammarRule("WHITESPACE")]
	private void mWHITESPACE()
	{
		EnterRule_WHITESPACE();
		EnterRule("WHITESPACE", 18);
		TraceIn("WHITESPACE", 18);
		try
		{
			int _type = WHITESPACE;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:83:2: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:83:6: ( ' ' | '\\t' | '\\r' | '\\n' )
			{
			DebugLocation(83, 6);
			if ((input.LA(1)>='\t' && input.LA(1)<='\n')||input.LA(1)=='\r'||input.LA(1)==' ')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(83, 35);
			_channel=Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WHITESPACE", 18);
			LeaveRule("WHITESPACE", 18);
			LeaveRule_WHITESPACE();
		}
	}
	// $ANTLR end "WHITESPACE"

	partial void EnterRule_STRING();
	partial void LeaveRule_STRING();

	// $ANTLR start "STRING"
	[GrammarRule("STRING")]
	private void mSTRING()
	{
		EnterRule_STRING();
		EnterRule("STRING", 19);
		TraceIn("STRING", 19);
		try
		{
			int _type = STRING;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:86:6: ( '\"' (~ ( '\\\\' | '\"' ) )* '\"' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:86:9: '\"' (~ ( '\\\\' | '\"' ) )* '\"'
			{
			DebugLocation(86, 9);
			Match('\"'); 
			DebugLocation(86, 13);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:86:13: (~ ( '\\\\' | '\"' ) )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if (((LA2_0>='\u0000' && LA2_0<='!')||(LA2_0>='#' && LA2_0<='[')||(LA2_0>=']' && LA2_0<='\uFFFF')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:
					{
					DebugLocation(86, 13);
					input.Consume();


					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }

			DebugLocation(86, 30);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING", 19);
			LeaveRule("STRING", 19);
			LeaveRule_STRING();
		}
	}
	// $ANTLR end "STRING"

	partial void EnterRule_POSITIVE_INTEGER16();
	partial void LeaveRule_POSITIVE_INTEGER16();

	// $ANTLR start "POSITIVE_INTEGER16"
	[GrammarRule("POSITIVE_INTEGER16")]
	private void mPOSITIVE_INTEGER16()
	{
		EnterRule_POSITIVE_INTEGER16();
		EnterRule("POSITIVE_INTEGER16", 20);
		TraceIn("POSITIVE_INTEGER16", 20);
		try
		{
			int _type = POSITIVE_INTEGER16;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:89:2: ( '0x' ( HEX_DIGIT )+ )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:89:4: '0x' ( HEX_DIGIT )+
			{
			DebugLocation(89, 4);
			Match("0x"); 

			DebugLocation(89, 9);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:89:9: ( HEX_DIGIT )+
			int cnt3=0;
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, false);
				int LA3_0 = input.LA(1);

				if (((LA3_0>='0' && LA3_0<='9')||(LA3_0>='A' && LA3_0<='F')||(LA3_0>='a' && LA3_0<='f')))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch (alt3)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:
					{
					DebugLocation(89, 9);
					input.Consume();


					}
					break;

				default:
					if (cnt3 >= 1)
						goto loop3;

					EarlyExitException eee3 = new EarlyExitException( 3, input );
					DebugRecognitionException(eee3);
					throw eee3;
				}
				cnt3++;
			}
			loop3:
				;

			} finally { DebugExitSubRule(3); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("POSITIVE_INTEGER16", 20);
			LeaveRule("POSITIVE_INTEGER16", 20);
			LeaveRule_POSITIVE_INTEGER16();
		}
	}
	// $ANTLR end "POSITIVE_INTEGER16"

	partial void EnterRule_POSITIVE_INTEGER10();
	partial void LeaveRule_POSITIVE_INTEGER10();

	// $ANTLR start "POSITIVE_INTEGER10"
	[GrammarRule("POSITIVE_INTEGER10")]
	private void mPOSITIVE_INTEGER10()
	{
		EnterRule_POSITIVE_INTEGER10();
		EnterRule("POSITIVE_INTEGER10", 21);
		TraceIn("POSITIVE_INTEGER10", 21);
		try
		{
			int _type = POSITIVE_INTEGER10;
			int _channel = DefaultTokenChannel;
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:2: ( ( '0' | ( POS_DIGIT ( DIGIT )* ) ) )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:4: ( '0' | ( POS_DIGIT ( DIGIT )* ) )
			{
			DebugLocation(92, 4);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:4: ( '0' | ( POS_DIGIT ( DIGIT )* ) )
			int alt5=2;
			try { DebugEnterSubRule(5);
			try { DebugEnterDecision(5, false);
			int LA5_0 = input.LA(1);

			if ((LA5_0=='0'))
			{
				alt5 = 1;
			}
			else if (((LA5_0>='1' && LA5_0<='9')))
			{
				alt5 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 5, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:6: '0'
				{
				DebugLocation(92, 6);
				Match('0'); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:12: ( POS_DIGIT ( DIGIT )* )
				{
				DebugLocation(92, 12);
				// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:12: ( POS_DIGIT ( DIGIT )* )
				DebugEnterAlt(1);
				// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:14: POS_DIGIT ( DIGIT )*
				{
				DebugLocation(92, 14);
				mPOS_DIGIT(); 
				DebugLocation(92, 24);
				// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:92:24: ( DIGIT )*
				try { DebugEnterSubRule(4);
				while (true)
				{
					int alt4=2;
					try { DebugEnterDecision(4, false);
					int LA4_0 = input.LA(1);

					if (((LA4_0>='0' && LA4_0<='9')))
					{
						alt4 = 1;
					}


					} finally { DebugExitDecision(4); }
					switch ( alt4 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:
						{
						DebugLocation(92, 24);
						input.Consume();


						}
						break;

					default:
						goto loop4;
					}
				}

				loop4:
					;

				} finally { DebugExitSubRule(4); }


				}


				}
				break;

			}
			} finally { DebugExitSubRule(5); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("POSITIVE_INTEGER10", 21);
			LeaveRule("POSITIVE_INTEGER10", 21);
			LeaveRule_POSITIVE_INTEGER10();
		}
	}
	// $ANTLR end "POSITIVE_INTEGER10"

	partial void EnterRule_POS_DIGIT();
	partial void LeaveRule_POS_DIGIT();

	// $ANTLR start "POS_DIGIT"
	[GrammarRule("POS_DIGIT")]
	private void mPOS_DIGIT()
	{
		EnterRule_POS_DIGIT();
		EnterRule("POS_DIGIT", 22);
		TraceIn("POS_DIGIT", 22);
		try
		{
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:95:2: ( '1' .. '9' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:
			{
			DebugLocation(95, 2);
			if ((input.LA(1)>='1' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("POS_DIGIT", 22);
			LeaveRule("POS_DIGIT", 22);
			LeaveRule_POS_DIGIT();
		}
	}
	// $ANTLR end "POS_DIGIT"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 23);
		TraceIn("DIGIT", 23);
		try
		{
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:98:2: ( '0' .. '9' )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:
			{
			DebugLocation(98, 2);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 23);
			LeaveRule("DIGIT", 23);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_HEX_DIGIT();
	partial void LeaveRule_HEX_DIGIT();

	// $ANTLR start "HEX_DIGIT"
	[GrammarRule("HEX_DIGIT")]
	private void mHEX_DIGIT()
	{
		EnterRule_HEX_DIGIT();
		EnterRule("HEX_DIGIT", 24);
		TraceIn("HEX_DIGIT", 24);
		try
		{
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:101:2: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:
			{
			DebugLocation(101, 2);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HEX_DIGIT", 24);
			LeaveRule("HEX_DIGIT", 24);
			LeaveRule_HEX_DIGIT();
		}
	}
	// $ANTLR end "HEX_DIGIT"

	public override void mTokens()
	{
		// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:8: ( BITFIELD | COMMA | ENUM | ENUM_BEGIN | ENUM_END | ENUM_ENTRY | EQUALS | EXTENDS | LBRACE | LEFT_SHIFT | LPAREN | META | NAMESPACE | RBRACE | RPAREN | SEMICOLON | ID | WHITESPACE | STRING | POSITIVE_INTEGER16 | POSITIVE_INTEGER10 )
		int alt6=21;
		try { DebugEnterDecision(6, false);
		try
		{
			alt6 = dfa6.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(6); }
		switch (alt6)
		{
		case 1:
			DebugEnterAlt(1);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:10: BITFIELD
			{
			DebugLocation(1, 10);
			mBITFIELD(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:19: COMMA
			{
			DebugLocation(1, 19);
			mCOMMA(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:25: ENUM
			{
			DebugLocation(1, 25);
			mENUM(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:30: ENUM_BEGIN
			{
			DebugLocation(1, 30);
			mENUM_BEGIN(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:41: ENUM_END
			{
			DebugLocation(1, 41);
			mENUM_END(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:50: ENUM_ENTRY
			{
			DebugLocation(1, 50);
			mENUM_ENTRY(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:61: EQUALS
			{
			DebugLocation(1, 61);
			mEQUALS(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:68: EXTENDS
			{
			DebugLocation(1, 68);
			mEXTENDS(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:76: LBRACE
			{
			DebugLocation(1, 76);
			mLBRACE(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:83: LEFT_SHIFT
			{
			DebugLocation(1, 83);
			mLEFT_SHIFT(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:94: LPAREN
			{
			DebugLocation(1, 94);
			mLPAREN(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:101: META
			{
			DebugLocation(1, 101);
			mMETA(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:106: NAMESPACE
			{
			DebugLocation(1, 106);
			mNAMESPACE(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:116: RBRACE
			{
			DebugLocation(1, 116);
			mRBRACE(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:123: RPAREN
			{
			DebugLocation(1, 123);
			mRPAREN(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:130: SEMICOLON
			{
			DebugLocation(1, 130);
			mSEMICOLON(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:140: ID
			{
			DebugLocation(1, 140);
			mID(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:143: WHITESPACE
			{
			DebugLocation(1, 143);
			mWHITESPACE(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:154: STRING
			{
			DebugLocation(1, 154);
			mSTRING(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:161: POSITIVE_INTEGER16
			{
			DebugLocation(1, 161);
			mPOSITIVE_INTEGER16(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// C:\\GitProjects\\CCGOnlinePublic\\CCGOnline\\CCGOnline\\Grammars\\EnumReflector.g:1:180: POSITIVE_INTEGER10
			{
			DebugLocation(1, 180);
			mPOSITIVE_INTEGER10(); 

			}
			break;

		}

	}


	#region DFA
	DFA6 dfa6;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa6 = new DFA6(this);
	}

	private class DFA6 : DFA
	{
		private const string DFA6_eotS =
			"\x1\xFFFF\x1\xE\x1\xFFFF\x2\xE\x5\xFFFF\x1\xE\x6\xFFFF\x1\x12\x1\xFFFF"+
			"\x5\xE\x1\xFFFF\x6\xE\x1\x24\x4\xE\x1\xFFFF\xA\xE\x1\x35\x1\xE\x1\x37"+
			"\x2\xE\x1\x3A\x1\xFFFF\x1\xE\x1\xFFFF\x2\xE\x1\xFFFF\x1\x3E\x1\x3F\x1"+
			"\x40\x3\xFFFF";
		private const string DFA6_eofS =
			"\x41\xFFFF";
		private const string DFA6_minS =
			"\x1\x9\x1\x49\x1\xFFFF\x2\x6E\x5\xFFFF\x1\x61\x6\xFFFF\x1\x78\x1\xFFFF"+
			"\x1\x54\x1\x75\x1\x74\x1\x75\x1\x6D\x1\xFFFF\x1\x46\x1\x6D\x1\x65\x1"+
			"\x6D\x1\x65\x1\x49\x1\x30\x1\x6E\x1\x42\x1\x73\x1\x45\x1\xFFFF\x1\x64"+
			"\x1\x65\x1\x6E\x1\x70\x1\x4C\x1\x73\x1\x67\x1\x64\x1\x61\x1\x44\x1\x30"+
			"\x1\x69\x1\x30\x1\x72\x1\x63\x1\x30\x1\xFFFF\x1\x6E\x1\xFFFF\x1\x79\x1"+
			"\x65\x1\xFFFF\x3\x30\x3\xFFFF";
		private const string DFA6_maxS =
			"\x1\x7D\x1\x49\x1\xFFFF\x1\x78\x1\x6E\x5\xFFFF\x1\x61\x6\xFFFF\x1\x78"+
			"\x1\xFFFF\x1\x54\x1\x75\x1\x74\x1\x75\x1\x6D\x1\xFFFF\x1\x46\x1\x6D\x1"+
			"\x65\x1\x6D\x1\x65\x1\x49\x1\x7A\x1\x6E\x1\x45\x1\x73\x1\x45\x1\xFFFF"+
			"\x1\x64\x1\x65\x1\x6E\x1\x70\x1\x4C\x1\x73\x1\x67\x1\x74\x1\x61\x1\x44"+
			"\x1\x7A\x1\x69\x1\x7A\x1\x72\x1\x63\x1\x7A\x1\xFFFF\x1\x6E\x1\xFFFF\x1"+
			"\x79\x1\x65\x1\xFFFF\x3\x7A\x3\xFFFF";
		private const string DFA6_acceptS =
			"\x2\xFFFF\x1\x2\x2\xFFFF\x1\x7\x1\x9\x1\xA\x1\xB\x1\xC\x1\xFFFF\x1\xE"+
			"\x1\xF\x1\x10\x1\x11\x1\x12\x1\x13\x1\xFFFF\x1\x15\x5\xFFFF\x1\x14\xB"+
			"\xFFFF\x1\x3\x10\xFFFF\x1\x8\x1\xFFFF\x1\x5\x2\xFFFF\x1\x1\x3\xFFFF\x1"+
			"\x4\x1\x6\x1\xD";
		private const string DFA6_specialS =
			"\x41\xFFFF}>";
		private static readonly string[] DFA6_transitionS =
			{
				"\x2\xF\x2\xFFFF\x1\xF\x12\xFFFF\x1\xF\x1\xFFFF\x1\x10\x5\xFFFF\x1\x8"+
				"\x1\xC\x2\xFFFF\x1\x2\x2\xFFFF\x1\x9\x1\x11\x9\x12\x1\xFFFF\x1\xD\x1"+
				"\x7\x1\x5\x3\xFFFF\x1\xE\x1\x1\x2\xE\x1\x4\x15\xE\x4\xFFFF\x1\xE\x1"+
				"\xFFFF\x4\xE\x1\x3\x8\xE\x1\xA\xC\xE\x1\x6\x1\xFFFF\x1\xB",
				"\x1\x13",
				"",
				"\x1\x14\x9\xFFFF\x1\x15",
				"\x1\x16",
				"",
				"",
				"",
				"",
				"",
				"\x1\x17",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x18",
				"",
				"\x1\x19",
				"\x1\x1A",
				"\x1\x1B",
				"\x1\x1C",
				"\x1\x1D",
				"",
				"\x1\x1E",
				"\x1\x1F",
				"\x1\x20",
				"\x1\x21",
				"\x1\x22",
				"\x1\x23",
				"\xA\xE\x7\xFFFF\x1A\xE\x4\xFFFF\x1\xE\x1\xFFFF\x1A\xE",
				"\x1\x25",
				"\x1\x26\x2\xFFFF\x1\x27",
				"\x1\x28",
				"\x1\x29",
				"",
				"\x1\x2A",
				"\x1\x2B",
				"\x1\x2C",
				"\x1\x2D",
				"\x1\x2E",
				"\x1\x2F",
				"\x1\x30",
				"\x1\x31\xF\xFFFF\x1\x32",
				"\x1\x33",
				"\x1\x34",
				"\xA\xE\x7\xFFFF\x1A\xE\x4\xFFFF\x1\xE\x1\xFFFF\x1A\xE",
				"\x1\x36",
				"\xA\xE\x7\xFFFF\x1A\xE\x4\xFFFF\x1\xE\x1\xFFFF\x1A\xE",
				"\x1\x38",
				"\x1\x39",
				"\xA\xE\x7\xFFFF\x1A\xE\x4\xFFFF\x1\xE\x1\xFFFF\x1A\xE",
				"",
				"\x1\x3B",
				"",
				"\x1\x3C",
				"\x1\x3D",
				"",
				"\xA\xE\x7\xFFFF\x1A\xE\x4\xFFFF\x1\xE\x1\xFFFF\x1A\xE",
				"\xA\xE\x7\xFFFF\x1A\xE\x4\xFFFF\x1\xE\x1\xFFFF\x1A\xE",
				"\xA\xE\x7\xFFFF\x1A\xE\x4\xFFFF\x1\xE\x1\xFFFF\x1A\xE",
				"",
				"",
				""
			};

		private static readonly short[] DFA6_eot = DFA.UnpackEncodedString(DFA6_eotS);
		private static readonly short[] DFA6_eof = DFA.UnpackEncodedString(DFA6_eofS);
		private static readonly char[] DFA6_min = DFA.UnpackEncodedStringToUnsignedChars(DFA6_minS);
		private static readonly char[] DFA6_max = DFA.UnpackEncodedStringToUnsignedChars(DFA6_maxS);
		private static readonly short[] DFA6_accept = DFA.UnpackEncodedString(DFA6_acceptS);
		private static readonly short[] DFA6_special = DFA.UnpackEncodedString(DFA6_specialS);
		private static readonly short[][] DFA6_transition;

		static DFA6()
		{
			int numStates = DFA6_transitionS.Length;
			DFA6_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA6_transition[i] = DFA.UnpackEncodedString(DFA6_transitionS[i]);
			}
		}

		public DFA6( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 6;
			this.eot = DFA6_eot;
			this.eof = DFA6_eof;
			this.min = DFA6_min;
			this.max = DFA6_max;
			this.accept = DFA6_accept;
			this.special = DFA6_special;
			this.transition = DFA6_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( BITFIELD | COMMA | ENUM | ENUM_BEGIN | ENUM_END | ENUM_ENTRY | EQUALS | EXTENDS | LBRACE | LEFT_SHIFT | LPAREN | META | NAMESPACE | RBRACE | RPAREN | SEMICOLON | ID | WHITESPACE | STRING | POSITIVE_INTEGER16 | POSITIVE_INTEGER10 );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}
